Unmaximize icon in titlebar
SpikeHD/Dorion pull request #178
Opened 2023-12-24 22:10 UTC by luximus-hunter

Continuation of https://github.com/SpikeHD/Dorion/pull/174 :)

Changes the icon of the maximize/unmaximize button to show a windowed mode icon. This way it signals to the user that it will put the window into a floating window again

Floating:

![image](https://github.com/SpikeHD/Dorion/assets/49814847/cdbe0323-11eb-42dd-8d5d-c59fef33643a)

Maximized:

![image](https://github.com/SpikeHD/Dorion/assets/49814847/a895e658-a9a3-41c3-97fc-f020af73a9c5)

2023-12-24 23:59 UTC, SpikeHD requested changes

2023-12-24 23:59 UTC, SpikeHD commented on src-tauri/injection/injection.js
> +  if (await window.__TAURI__.invoke('is_maximized')) {
You can actually get the state of the window from within the JS api, no need for it's own Tauri command:
https://tauri.app/v1/api/js/window/#ismaximized

`window.__TAURI__.window.appWindow.isMaximized()` should do it

2023-12-24 23:59 UTC, SpikeHD commented on src-tauri/injection/injection.js
> +  window.addEventListener('resize', setMaximizeIcon)
This is gonna call `setMaximizeIcon` a *bunch* (like, 100 times per 3 seconds of resizing) if the user is just adjusting their window size. While I don't see this realistically being a problem, we should prefer [the Tauri WINDOW_RESIZED event](https://tauri.app/v1/api/js/event#taurievent), which is only called once a resize is completed (and from my testing, only when the state of maximization is changed, so it's perfect!)

Something like this should work:
```js
__TAURI__.event.listen(
  __TAURI__.event.TauriEvent.WINDOW_RESIZED,
  setMaximizeIcon
)
```

2023-12-25 09:27 UTC, SpikeHD commented
Haha, did you by any chance autoformat the entire `injection.js` file? Most recent commit (b3a5e831c48d271b26b9118d8a1395e925b74b4b) adds a bunch of semicolons and double quotes, which don't follow the eslint rules (which the "Check frontend" job should be catching but whatever, another problem for another day).

Running `pnpm codefix` and committing that should bring you back to about what it should be.

2023-12-25 09:30 UTC, luximus-hunter commented
Oh shi-

2023-12-25 09:39 UTC, SpikeHD commented
Gonna just fix the ESLint styling myself, thank you for the contribution!

2023-12-25 09:39 UTC, merged